#!/bin/sh
# Copyright (C) 2021 Harold Grovesteen
#
# This file is part of SATK.
#
#     SATK is free software: you can redistribute it and/or modify
#     it under the terms of the GNU General Public License as published by
#     the Free Software Foundation, either version 3 of the License, or
#     (at your option) any later version.
#
#     SATK is distributed in the hope that it will be useful,
#     but WITHOUT ANY WARRANTY; without even the implied warranty of
#     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#     GNU General Public License for more details.
#
#     You should have received a copy of the GNU General Public License
#     along with SATK.  If not, see <http://www.gnu.org/licenses/>.

# This script MUST be executed from SATK's samples/guide/pgm1 directory
# Just type ./ipl in the guide program directory.

# IPL the sample program in Hercules.

datetime()
{
	sfx=$(date +%Y%m%d.%H%M%S)
}
datetime   # set $sfx (the date and time of the run) for later use

# Change this variable for your environment
SIMHREPO=${HOME}/simh/simhrepo       # simh location directory
SIMH=${SIMHREPO}/BIN/ibm360          # simh simulator
TEST=${HOME}/simh/simh_tests/echo
STARTUP=${TEST}/echo.ini      # Simulator start up file

echo "at the SimH prompt type: boot cdr0"
echo "to exit the program type: quit"
echo "to exit the simulator type: quit"
${SIMH} ${STARTUP}
