#!/bin/sh
# Copyright 2021 Harold Grovesteen
#
# MIT License:
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.

# To execute, just type ./med in the simh_tests/hello directory

datetime()
{
	sfx=$(date +%Y%m%d.%H%M%S)
}
datetime   # set $sfx (the date and time of the run) for later use

# Change this variable for your environment
REPO=${HOME}/SATKREPO/SATK      # SATK repository from github

# This variable is for the author's use.  Just leave it alone
#REPO=${HOME}/SATKCLONE

# IPLASMA related script variables
IPLASMA=${REPO}/tools/iplasma.py    # The IPL medium creation tool

# Create the IPL medium
${IPLASMA} -v -f ld -d CARD -m echo.deck --asa=ASAREGN.bin \
           ldid/echo.txt >> iplasma-${sfx}.txt
